name: Deploy to AWS via ECR + Elastic Beanstalk

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPO: ${{ secrets.AWS_ECR_REPOSITORY }}
  S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
  EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        IMAGE_URI=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:$IMAGE_TAG

        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Generate Dockerrun.aws.json
      run: |
        cat > Dockerrun.aws.json <<EOF
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "${IMAGE_URI}",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": "8080"
            }
          ]
        }
        EOF

    - name: Create ZIP with Dockerrun.aws.json only
      run: zip deploy.zip Dockerrun.aws.json

    - name: Upload to S3
      run: |
        VERSION_LABEL="go-api-${{ github.sha }}"
        S3_KEY="versions/$VERSION_LABEL.zip"

        aws s3 cp deploy.zip s3://$S3_BUCKET/$S3_KEY

        echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
        echo "S3_KEY=$S3_KEY" >> $GITHUB_ENV

    - name: Create new EBS application version
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name $EB_APP_NAME \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket=$S3_BUCKET,S3Key=$S3_KEY

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk update-environment \
          --environment-name $EB_ENV_NAME \
          --version-label $VERSION_LABEL
